"""create users table

Revision ID: 193671e9e92a
Revises:
Create Date: 2025-09-02 17:44:09.097704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193671e9e92a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False, unique=True),
    sa.Column('email', sa.String(), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('PK_new_table'))
    # )
    # ### end Alembic commands ###
