"""update password in users table

Revision ID: b79db747bfc5
Revises: e18a7a9e3bb1
Create Date: 2025-09-03 11:19:34.617703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79db747bfc5'
down_revision: Union[str, Sequence[str], None] = 'e18a7a9e3bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column('encrypted_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
